
version: '3.8'

services:
  todo-front:
    container_name: todo-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
